### ISSUE TITLE
update typer exercise by adding confirm picture in some cases

### ISSUE THREAD

**Issue by x-spert** [tehciolo/bookrack#33]
- [x] update typer exercise by adding (replace one picture with one colored or with border..) confirm picture in some cases:

Example of exercises:
_Deutch 1, vol 1:_
- [x] pg. 52, ex. 3 - "la validare daca se poate sa se coloreze si obiectul - in cazul in care au scris corect sa se inverzeasca, ingalbeneasca elementele din imagine"
  _Deutch 1, vol2:_
- [x] pg. 11, ex. 1 - "daca s-ar putea colora animalele la validare"
- [x] pg. 12, ex. 2 - "daca s-ar putea colora animalele la validare"

_Deutch 3, vol 2:_
- [x] pg. 71, ex. 3 - "la validare sa apara selectata imaginea corecta ca sa nu mai facem altul de unit text cu imagine"

**Comment by tehciolo** [comment]
Am adaugat posibilitatea de a avea o imagine colorata care apare la validare. 

Ea este conditionata insa de o imagine initiala (trebuie sa ai default state).

Am facut update la toate cartile cu exercitiul updatat si am terminat pg52ex3 (pozele sunt urcate pe ftp)

De celelalte 2 exercitii nu am mai avut timp. pg11ex1 probabil mi-ar lua in jur de 20 de minute dar la celalalt e foarte mult de editat la poze.

**Comment by tehciolo** [comment]
Credeam ca te-ai uitat tu...

Doar primul exercitiu e de tip typer si chiar toate sunt diferite. Mai e un type si un picker.

cc @x-spert
